config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :questions, except: [:show, :new, :index]
  resource :session, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  belongs_to :owner, class_name: 'User', required: false
 
  validates :text, :user, presence: true
  validates :text, length: {maximum: 255}
  
  # #Популярные колбеки
  # before_validation :before_validation
  # after_validation :after_validation
  # before_save :before_save
  # after_save :after_save
  # before_create :before_create
  # after_create :after_create
  # after_save :after_save

  # before_update :before_update
  # after_update :after_update

  # before_destroy :before_destroy
  # after_destroy :after_destroy


  # private
  # ['validation', 'save', 'create', 'update', 'destroy'].each do |action|
  #    ['before', 'after'].each do |time|
  #      define_method("#{time}_#{action}") do 
  #        puts "*****> #{time} #{action}"
  #      end
  #    end
  # end
 end

app/models/user.rb
require 'openssl' 

class User < ApplicationRecord
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions, dependent: :destroy
  
  validates :email, :username, presence: true
  validates :email, :username, uniqueness: true, on: [:create, :update]
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP}, on: [:create, :update]
  validates :username, length: {maximum: 40}, format:{ with: /\A[a-zA-Z\d_]+\z/}

  attr_accessor :password

  mount_uploader :avatar_url, AvatarUploader

  validates_presence_of :password, on: :create # <=> validates :password, presence: true
  validates_confirmation_of :password

  before_save :encrypt_password, :username_to_downcase
  def encrypt_password
    if self.password.present?
      #создаем т. н. соль - рандомная строка, усложнаяющая задачу хакерам
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      #создаем хеш пароля - длинная уникальная строка из которой невозможно восстановить исходный пароль
      self.password_hash = User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST))
    end
  end

  # служебный метод, преобразует бинарную строку в 16ный формат, для удобства хранения
  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)
    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end

  def username_to_downcase
     self.username.downcase!
  end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # хелпер для доступа во вьюхах
  helper_method :current_user 

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: "Доступ запрещен!"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user,  except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.owner = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user)
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user)
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален'
  end

  private
    def load_question
      @question = Question.find(params[:id])
    end

    def question_params
      if current_user.present? && params[:question][:user_id].to_i == current_user.id
        params.require(:question).permit(:user_id, :text, :answer, :owner_id)
      else
        params.require(:question).permit(:user_id, :text)
      end
    end

    def authorize_user
      reject_user unless @question.user == current_user
    end

    def check_captcha(model)
      if current_user.present?
        true
      else
        verify_recaptcha(model: model)
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = 'Не правильный email или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, except: [:index, :create, :new]
  before_action :authorize_user,  except: [:index, :new, :create, :show, :destroy]
  
  def index
    @users = User.all
  end

  def new
    redirect_to root_url, alert: "Вы уже залогинены" if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: "Вы уже залогинены" if current_user.present? 
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Пользователь успешно зарегистрирован'
    else
      render :edit
    end
  end

  def edit
  end

  def update 
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные успешно сохранены'
    else
      render :edit
    end
  end
  
  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end
  
  def destroy
    session[:user_id] = nil
    @user.destroy
    redirect_to root_url, notice: 'Аккаунт удален'
  end
   
  private
 
  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,:name, :username, :avatar_url, :background_color)
  end

  def authorize_user
    reject_user unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url.url
    else
      asset_path 'avatar.jpg'
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}" 
  end

  def question_owner(question)
    question.owner.present? ? (link_to "@#{question.owner.username}", user_path(question.owner.id)) : ("Анон")
  end
end

app/helpers/qustions_helper.rb
module QustionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= javascript_include_tag 'application'  %>
  </head>

  <body>
    <div class="header">
      <div class="container">
        <div class="header-logo">
          <h1 class="header-title">
            <%= link_to 'Хорошие вопросы', root_path%>
          </h1>
        </div>
        <div class="header-nav">
          <% if current_user %>
            <%= link_to "@#{current_user.username}", user_path(current_user)%>
            <%= link_to 'Выйти', session_path, data: {method: :delete} %>
          <% else %>
            <%= link_to 'Зарегистрироваться', new_user_path, class: 'button button-light button-small'%>
            <%= link_to 'Войти', new_session_path, class: 'button button-light button-small'%>
          <% end %>
        </div>
      </div>
    </div>
    <div class="content">
      <div class="container">
      <% if flash.any?%>
        <div class="content-wrapper buffer-both">
        <% flash.each do |name, message|%>
          <%= content_tag :div, message, class: "flash-#{name}"%>
        <% end %>
        </div>
      <% end %>
        <%= yield %>
      </div>
    </div>
    
  </body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f|%>
    <% if @question.errors.any?%>
        <div class="form-errors">
          <ul>
            <% for message in @question.errors.full_messages%>
              <li class="form-error-message"><%= message%></li> 
            <% end %>
          </ul>
        </div>
    <%end%>
  
  <%= f.hidden_field :user_id%>
  <%= f.hidden_field :owner_id%>

  <div class="form-field">
    <%= f.label :text, 'Вопрос', class: 'form-label'%>
    <%= f.text_field :text, class: 'form-textarea'%>
  </div>

  <% if current_user.present? && current_user == @question.user%>
    <div class="form-field">
      <%= f.label :answer, 'Ответ', class: 'form-label'%>
      <%= f.text_field :answer, class: 'form-textarea'%>
    </div>
  <%end%>

  <%= recaptcha_tags unless current_user.present? %>

  <div class="form-action buffer-both">
    <%= f.submit 'Сохранить', class: 'button button-small button-dark'%> или
    <%= link_to 'вернуться', user_path(@question.user)%>
  </div>

  <%end%>
</div>

app/views/questions/_question.html.erb
<%# Это фрагмет (паршал, partial) для вывода вопроса.В нем определена %>
<%# локальная переменная question, в которую при вызове будет передан как в %>
<%# метод ruby объект после ключа (object: @question) %>
<% question ||= nil %>
<% action_icon = question.answer.blank? ? 'reply' : 'pencil' %>

<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer %>
      </div>
    <% end %>

    <div class="question-date">
      <%= question_owner(question) %>  <%= l(question.created_at, format: :short) %>
    </div>
    
  </div>
  <% if question.user == current_user%>
    <div class="question-actions">
      <%= link_to fa_icon(action_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question), 
                  method: :delete, data: {confirm: 'Точно хотите удалить вопрос?'}%>
    </div>
  <% end%>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>
  
  <div class="column-1-2">
    <%= render 'form'%>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container container-wrappe buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="form">
    <%= form_for @user do |f|%>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages%>
            <li class="form-error-message"><%= message%></li> 
            <% end %>
          </ul>
        </div>
       <% end %>
      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label'%>
        <%= f.text_field :username, class: 'form-text-field'%>
      </div>
      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label'%>
        <%= f.text_field :name, class: 'form-text-field'%>      
      </div>
      <div class="form-field">
        <%= f.label :avatar_url, 'Аватар', class: 'form-label'%>
        <p> <%= image_tag(@user.avatar_url.thumb.url) if @user.avatar_url? %></p>
        <%= f.file_field  :avatar_url, class: 'form-text-field'%>      
      </div>
      <div class="form-field">
        <%= f.label :background_color, 'Цвет фона', class: 'form-label'%>
        <%= f.color_field :background_color, value: @user.background_color%>
      </div>
      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label'%>
        <%= f.password_field :password, class: 'form-text-field'%>
      </div>
      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label'%>
        <%= f.password_field :password_confirmation, class: 'form-text-field'%>
      </div>
      <div class="form-action">
        <%= f.submit 'Сохранить', class: 'button button-small button-green'%>
      </div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%# Этот шаблон отрисуется, когда пользователь захочет посмотреть список пользователей %>
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <%# Этот код выводит каждого пользователя в цикле %>
  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%# Пользуемся аж тремя хелперами %>
          <%# link_to — генерирует ссылку %>
          <%# image_tag — генерирует картинку %>
          <%# user_avatar — достает из пользователя ссылку на картинку или подставляет дефолтную %>
          <%# Хелпер user_path(user) возвращает относительный путь %>
          <%# страницы пользователя, например /users/1 %>
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        
        </div>
          @<%= user.username %>
      </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container container-wrappe buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="form">
    <%= form_for @user do |f|%>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages%>
            <li class="form-error-message"><%= message%></li> 
            <% end %>
          </ul>
        </div>
       <% end %>
      <div class="form-field">
        <%= f.label :email, 'Логин(email)', class: 'form-label'%>
        <%= f.text_field :email, class: 'form-text-field'%>
      </div>
      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label'%>
        <%= f.text_field :username, class: 'form-text-field'%>
      </div>
      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label'%>
        <%= f.text_field :name, class: 'form-text-field'%>      
      </div>
      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label'%>
        <%= f.password_field :password, class: 'form-text-field'%>
      </div>
      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label'%>
        <%= f.password_field :password_confirmation, class: 'form-text-field'%>
      </div>
      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-green'%>
      </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background-color:<%= @user.background_color %>">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="buffer-both">
    <%= link_to 'удалить профиль', user_path(@user), class: 'text-small', 
            method: :delete, data: {confirm: 'Точно хотите удалить пользователя?'} if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <%# Выводим счетчики вопросов в три колонки. Обратите внимание, что тут %>
  <%# в пору использовать наш любимый склонятор. На эту тему смотрите ДЗ. %>
  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p>вопросов</p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <p>ответов</p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <p>безответных</p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>    
         
      <%= recaptcha_tags size: 'compact' unless current_user.present? %>      
      <div class="form-action">
        <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>